#ZoneMap = {
#    1: {
#        "name": "旧都列车",
#        "level": {1: "外围", 2: "前线", 3: "内部", 4: "腹地", 5: "核心"},
#    },
#    2: {
#        "name": "施工废墟",
#        "level": {1: "前线", 2: "内部", 3: "腹地", 4: "核心"},
#    },
#}

# 模型训练集大部分来自旧都列车，脚本刷图目前旧都列车最稳定，其他图bug会比较多，刷零号业绩旧都列车前线最快，练度够可以直接刷前线
targetMap:
    level: 1                # 默认等级 1: 外围
    zone: 1                 # 默认区域 1: 旧都列车
modeSelect: 1               # 模式选择 1: 全通关  2: 刷零号业绩  3：零号银行
maxFightTime: 150           # 最大战斗时间，单场战斗时间默认为150s，超过150s会重开(部分战斗场景需要跑图，目前还没进行相关处理，遇到这种情况会退掉重开)
maxMapTime: 900             # 在地图内最大时间默认为900s，超过最大时间未通关地图会重开
hasBoom: False              # 是否解锁炸弹
useGpu: True                # 是否使用GPU，默认True, 使用GPU会加速模型训练,如果改为False，会强制使用CPU进行OCR识别
fightTactics:
    # 鼠标左键攻击5次，每次按住0.2s，间隔0.1s
    -   key: "left"          # 按键 left为鼠标左键，right为鼠标右键，middle为鼠标中键
        type: "press"        # 按住 press为按住， down为按下， up为松开
        duration: 0.1        # 按住时间  duration为按住时间，press时有效
        delay: 0.2          # 本次操作执行完毕后延迟时间 默认为0.1
        repeat: 5           # 本次操作重复次数
    # 键盘按键e按住0.5s，如果未设置 delay 默认为0.1，如果未设置 clicks 默认为1
    -   key: "e"         # 按键
        type: "press"   # 按住
        duration: 0.5   # 按住时间
    # 等待0.5s
    -   delay: 0.5    # 等待时间
    # 按键盘按键space
    -   key: "space"      # 按键
        type: "press"      # 点击

    # 冲刺蓄力攻击
    -   key: "w"
        type: "down"
        delay: 0          # 执行完毕后不进行延迟

    # 按键盘按键shift
    -   key: "shift"      # 按键
        type: "press"      # 按下

    -   key: "shift"      # 按键
        type: "down"      # 按下
    # 等待0.5s
    -   delay: 0.5        # 等待时间
    # 鼠标左键按下
    -   key: "left"      # 按键
        type: "down"      # 按下
        duration: 1.3    # 按住时间
    # 松开w
    -   key: "w"
        type: "up"
        delay: 0
    # 松开shift
    -   key: "shift"
        type: "up"
